# paths to the man pages for conversion to html
MANS = \
       /usr/share/man/man1/finddeps-distmeta.1.gz                 \
       /usr/share/man/man1/finddeps-linked.1.gz                   \
       /usr/share/man/man1/finddisappeared.1.gz                   \
       /usr/share/man/man1/finddisowned.1.gz                      \
       /usr/share/man/man1/findredundantdeps.1.gz                 \
       /usr/share/man/man1/pkgdiff.1.gz                           \
       /usr/share/man/man1/pkginfo.1.gz                           \
       /usr/share/man/man1/pkglint.1.gz                           \
       /usr/share/man/man1/pkgman-cat.1.gz                        \
       /usr/share/man/man1/pkgman-current.1.gz                    \
       /usr/share/man/man1/pkgman-dep.1.gz                        \
       /usr/share/man/man1/pkgman-diff.1.gz                       \
       /usr/share/man/man1/pkgman-dsearch.1.gz                    \
       /usr/share/man/man1/pkgman-dumpconfig.1.gz                 \
       /usr/share/man/man1/pkgman-fsearch.1.gz                    \
       /usr/share/man/man1/pkgman-info.1.gz                       \
       /usr/share/man/man1/pkgman-isinst.1.gz                     \
       /usr/share/man/man1/pkgman-list-dup.1.gz                   \
       /usr/share/man/man1/pkgman-list-locked.1.gz                \
       /usr/share/man/man1/pkgman-list-nodependents.1.gz          \
       /usr/share/man/man1/pkgman-list-orphans.1.gz               \
       /usr/share/man/man1/pkgman-list.1.gz                       \
       /usr/share/man/man1/pkgman-ls.1.gz                         \
       /usr/share/man/man1/pkgman-path.1.gz                       \
       /usr/share/man/man1/pkgman-printf.1.gz                     \
       /usr/share/man/man1/pkgman-rdep.1.gz                       \
       /usr/share/man/man1/pkgman-readme.1.gz                     \
       /usr/share/man/man1/pkgman-search.1.gz                     \
       /usr/share/man/man1/pkgman.1.gz                            \
       /usr/share/man/man1/revdep.1.gz                            \
       /usr/share/man/man5/Pkgfile.5.gz                           \
       /usr/share/man/man5/crypttab.5.gz                          \
       /usr/share/man/man5/mkinitramfs.config.5.gz                \
       /usr/share/man/man5/mkrootfs.config.5.gz                   \
       /usr/share/man/man5/pkgadd.conf.5.gz                       \
       /usr/share/man/man5/pkgman.conf.5.gz                       \
       /usr/share/man/man5/pkgmk.conf.5.gz                        \
       /usr/share/man/man5/rc.conf.5.gz                           \
       /usr/share/man/man5/rejmerge.conf.5.gz                     \
       /usr/share/man/man7/mkinitramfs.cmdline.7.gz               \
       /usr/share/man/man7/mkinitramfs.hooks.7.gz                 \
       /usr/share/man/man7/mkrootfs.release.7.gz                  \
       /usr/share/man/man8/cryptmount.8.gz                        \
       /usr/share/man/man8/mkinitramfs.8.gz                       \
       /usr/share/man/man8/mkrootfs.8.gz                          \
       /usr/share/man/man8/pkgadd.8.gz                            \
       /usr/share/man/man8/pkgman-edit.8.gz                       \
       /usr/share/man/man8/pkgman-install.8.gz                    \
       /usr/share/man/man8/pkgman-lock.8.gz                       \
       /usr/share/man/man8/pkgman-remove.8.gz                     \
       /usr/share/man/man8/pkgman-sysup.8.gz                      \
       /usr/share/man/man8/pkgman-unlock.8.gz                     \
       /usr/share/man/man8/pkgman-update.8.gz                     \
       /usr/share/man/man8/pkgmk.8.gz                             \
       /usr/share/man/man8/pkgrm.8.gz                             \
       /usr/share/man/man8/rc.8.gz                                \
       /usr/share/man/man8/rejmerge.8.gz                          \
       /usr/share/man/man8/seedrng.8.gz                           \
       /usr/share/man/man8/start-stop-daemon.8.gz                 \

# End of file.
