=pod

=encoding utf-8

=begin html

  <!-- Logo -->
  <header>
    <img alt="Zeppe-Lin" class="logo" src="https://github.com/zeppe-lin/artwork/blob/master/logo-big-2color.png?raw=true">
  </header>

=end html

=head1 INTRODUCTION

Zeppe-Lin is a lightweight source-based GNU/Linux distribution for the
x86-64 architecture targeted at experienced Linux users.  The primary
focus of this distribution is to keep it simple, which is reflected in
a straightforward tar.gz-based package system, BSD-style initscripts,
and a relatively small collection of trimmed packages.  The secondary
focus is the utilization of new Linux features and recent tools and
libraries.  Zeppe-Lin also has a
L<pkgsrc|http://zeppel.ink/man/handbook.7.html#THE-PACKAGES-SOURCES-SYSTEM>
system which makes it easy to install and upgrade applications.

=begin html

  <!-- GitHub release (latest by date) -->
  <a href="https://github.com/orgs/zeppe-lin/discussions/1">
    <img src="https://img.shields.io/github/v/release/zeppe-lin/pkgsrc-core?color=2c5e36&display_name=tag&label=CURRENT%20RELEASE&logo=linux&logoColor=white&style=for-the-badge" alt="Goto Current Release Announcement.">
  </a>

=end html

=head1 DOCUMENTATION

=head2 Handbook

The L<handbook(7)|https://zeppel.ink/man/handbook.7.html>
covers the installation, configuration, and administration of
Zeppe-Lin.

=head2 Release Notes and Errata

The L<release announcement page|https://github.com/orgs/zeppe-lin/discussions/1>
contains important information about updates, changes, and bug fixes in
the current Zeppe-Lin release. Whereas the
L<projects page|https://github.com/orgs/zeppe-lin/projects>
contains the tasks and issues for current and next release.

=head1 DOWNLOAD

Before downloading Zeppe-Lin, please read the
L<handbook(7)|https://zeppel.ink/man/handbook.7.html> to be sure your
hardware is supported, and you know how to install it.  Then look at the
L<release announcement|https://github.com/orgs/zeppe-lin/discussions/1>
for important information about the current Zeppe-Lin release and
download links.

=head1 COMMUNITY

For announcements, discussions, and support, please check our GitHub
L<discussions page|https://github.com/orgs/zeppe-lin/discussions>
and Libera.Chat L<#zeppe-lin channel|https://web.libera.chat/#zeppe-lin>.

=cut

# vim: sw=2 ts=2 sts=2 et cc=72 tw=70
# End of file.
